### PR TITLE
Next release: Rewrite of GSL.jl, using GSL v2.5

### PR DESCRIPTION
**Pull request by ludvigak**
I would like to suggest opening a new release branch based on this PR, to be merged into master and released as v0.5.0 in the near future.

This is an almost complete rewrite of the package. Julia wrappers are now created using a script that parses the GSL headers and docs using regular expressions. Most structs and library calls get correctly interfaced, which means that a lot of features are working out of the box. On top of this are some convenience wrappers, generated using a set of heuristic rules (same as before, more or less),  and manually written macros to simplify wrapping of functions that are passed to GSL.

README of this new version: https://github.com/ludvigak/GSL.jl/blob/gsl2/README.md

Notable new features:
- Wrappers are generated based on the headers of GSL v2.5.
- Wrappers have docstrings generated using the GSL docs.
- GSL global variables are loaded at init using `cglobal`.

As a bonus, all examples in `examples/` are now working.

This will probably break compability with earlier versions in many ways, but two major causes are:
- The `gsl_` prefix is added to all interfaces. This is to distinguish them from secondary wrappers (convenience functions), and to allow a more direct access to the library, for those who wish.
- Support for Julia versions earlier than 1.0 is dropped. This might not be absolutely necessary, but I see no point in supporting Julia 0.6 going forward.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Wow, great work!

**Comment by simonbyrne** [comment]
I really like that you autogenerated the documentation as well.

Once you are generally satisfied, I think the best option will be to merge it into master, and let people go from there (I see that you've already created a `release-0.5` branch for the current version). We can let people try it out for a while, maybe go through the reverse dependencies, etc., and aim to tag a new release in a week or two?

**Comment by yuyichao** [comment]
> The gsl_ prefix is added to all interfaces. This is to distinguish them from secondary wrappers (convenience functions), and to allow a more direct access to the library, for those who wish.

:-1: :-1: :-1: Unless all the functions that doesn't have an secondary wrapper also get's an alias. Also, this is exactly what namespace ((sub)modules) are for.

**Comment by ludvigak** [comment]
> > The gsl_ prefix is added to all interfaces. This is to distinguish them from secondary wrappers (convenience functions), and to allow a more direct access to the library, for those who wish.
> 
>    Unless all the functions that doesn't have a secondary wrapper also get's an alias. Also, this is exactly what namespace ((sub)modules) are for.

I know this is a major change, so I'd be happy to discuss how to structure it. My main thinking was basically that `gsl_` functions should behave as Julia versions of the functions defined in the GSL header files, and from there I just figured that secondary wrappers should be distinguishable by missing the prefix. Also, I have found that GSL.jl exports _a lot_ of symbols, and they pollute the namespace less if most of them have the prefix (relatively few functions have secondary wrappers). What would be the motivation for giving an alias to functions without a secondary wrapper?

To divide up how things are `export`ed by using submodules sounds interesting. Any suggestions on how to do this? I've never structured a module this big before.
- One option would be to mimic how things are included when using GSL in C, i.e. something like `using GSL.gsl_sf_bessel` would correspond to `#include <gsl/gsl_sf_bessel.h>`. That would require some reorganization of the code generation though, especially if types are to be handled like that.

**Comment by ludvigak** [comment]
On a separate note: I considered giving the arguments of the direct interface functions specified types, but decided to leave it to `ccall` to complain if it doesn't know how to do the conversion. As an example, this allows passing a `gsl_result` struct to a function without problem, even if the `ccall` then specifies the argument to be `Ref{gsl_result}`, since it knows how to convert.

**Comment by ludvigak** [comment]
> Once you are generally satisfied, I think the best option will be to merge it into master, and let others build on it (I see that you've already created a `release-0.5` branch for the current version). We can let people try it out for a while, maybe go through the reverse dependencies, etc., and aim to tag a new release in a week or two?

I'm still figuring out what a good format for contributing is, that's why I created the empty release branch and then opened this PR. Let me know if there's a better way :)

**Comment by yuyichao** [comment]
> My main thinking was basically that gsl_ functions should behave as Julia versions of the functions defined in the GSL header files, and from there I just figured that secondary wrappers should be distinguishable by missing the prefix.

I have absolutely no problem having such a distinction but for one the prefix is just wrong. And,

> Also, I have found that GSL.jl exports a lot of symbols, and they pollute the namespace less if most of them have the prefix (relatively few functions have secondary wrappers).

Both of these are just saying that since you don't want to use the `GSL` module as namespace but a C-style namespace with `gsl_` prefix. As I said, julia has namespace, that's `module` and I see no reason of using C-style namespace for anything. This means that, for the direct and indirect wrapper, you should use a submodule inside `GSL` (OpenCL.jl uses [an `api` module for this purpose](https://github.com/JuliaGPU/OpenCL.jl/blob/fa0268f0413cbdd5b159ed77af6efe353dc08df1/src/api.jl) I don't think the name fit but you can see the point). And if you want to avoid namespace polution, just don't import all those names. You can either just don't export them, or just recommend the users to `import GSL` instead of `using GSL` with the exported symbol only serve as a easy to search list for the user and for convinience for quick hack/REPL use.

> What would be the motivation for giving an alias to functions without a secondary wrapper?

Because many functions are stand-alone enough to be treated as the same level of API like other functions with a secondary wrapper. As a matter of fact, the names are used by the users, and most users won't and shouldn't care if a high level functionality he need is implemented directly in libgsl or as a wrapper of a few functions in C. In another word, for the user, your "secondary wrapper" should mean "functions meant to be used directly by users" since this is the only property a user should ever care about (everything else is implementation detail that shouldn't be exposed). This concept should have obvious overlap with "functions directly exposed by libgsl" and such overlapping case is what you should have both versions for the users.

> `using GSL.gsl_sf_bessel` would correspond to `#include <gsl/gsl_sf_bessel.h>`

I don't know how well libgsl is organized but if it is very well organized, such a correspondance could be good. Having too many submodules could in the general case makes it harder for users to use things but if you roughly makes sure the division is roughly replacing `_` with `.` that shouldn't be a problem. This seems non-trivial to do for everything though since `GSL.sf.laguerre.1` isn't an allowed name.

> I considered giving the arguments of the direct interface functions specified types

That's very wrong. Don't do that. That's the other thing I specifically checked about and glad to see there's no type constraints.

**Comment by yuyichao** [comment]
> This seems non-trivial to do for everything though since `GSL.sf.laguerre.1` isn't an allowed name.

From a 2-minute look at GSL headers it seems that having one level submodule seems to match GSL's organization pretty well. (e.g. `GSL.blas`, `GSL.block`, `GSL.fft`, `GSL.sf`, `GSL.permute` etc.)

**Comment by yuyichao** [comment]
> I'm still figuring out what a good format for contributing is

Not sure if others has preference but you can just use a branch in this REPL and open a PR against master from there. I assume the only reason to merge in a branch here that is master is to make it easier for ppl to test so just opening a branch should be good enough. (Unclear how well Pkg support force push though...)

**Comment by simonbyrne** [comment]
> From a 2-minute look at GSL headers it seems that having one level submodule seems to match GSL's organization pretty well. (e.g. `GSL.blas`, `GSL.block`, `GSL.fft`, `GSL.sf`, `GSL.permute` etc.)

That seems like a good idea. Maybe go with the Julia capitalization convention though? (`GSL.BLAS`, `GSL.Block`, `GSL.FFT``, etc.).

> Not sure if others has preference but you can just use a branch in this REPL and open a PR against master from there.

What did you mean by "use a branch in this REPL"?

**Comment by ludvigak** [comment]
@yuyichao I get your points. Using a more Julia-style namespace setup does seem attractive. One issue with dividing the namespace into submodules would be that in many cases the functions named `gsl_[sub]_*` operator on a type named `gsl_[sub]` (e.g. `gsl_wavelet_*` work with the type `gsl_wavelet`).

If we capitalized the namespaces (@simonbyrne ), then this would not be as acute, as `GSL.WAVELET` would be a submoduke and `GSL.wavelet` a type (or `GSL.WAVELET.wavelet`), but to me this setup looks like it's made for confusing people.

**Comment by simonbyrne** [comment]
> If we capitalized the namespaces (@simonbyrne ), then this would not be as acute, as `GSL.Wavelet` could be a submodule and `GSL.wavelet` a type (or `GSL.Wavelet.wavelet`), but to me this setup looks like it's made for confusing people.

Well, the Julia convention is to capitalise types as well, so that wouldn't help. However there is a common trick of pluralising the module name, e.g. `GSL.Wavelets.Wavelet`, `GSL.Histograms.Histogram`, which could work?

> I think he could've meant "repo"

Ah, that makes sense. I'm happy for it to make it `master`, since I don't think anyone is to keen to maintain separate branches, but if people want to wait we could call it something like `develop` until it's ready.

**Comment by ludvigak** [comment]
> Well, the Julia convention is to capitalise types as well, so that wouldn't help. However there is a common trick of pluralising the module name, e.g. `GSL.Wavelets.Wavelet`, `GSL.Histograms.Histogram`, which could work?

I've always thought of GSL.jl as a pretty thin Julia wrapper over the C library GSL, and as such I've always relied on the GSL documentation to figure out how to use it. I think trying to fit the GSL names into Julia-style namespaces makes it harder to directly use the documentation like this.

To some extent I think it comes down to ambitious you want to be in making this have the look and feel of a Julia package rather than a wrapper to a C library.

I do however see that it makes sense to drop `gsl_` and encourage people to `import GSL`. Then we could keep the direct wrappers in a submodule named `GSL.[Something]`.

> Ah, that makes sense. I'm happy for it to make it `master`, since I don't think anyone is to keen to maintain separate branches, but if people want to wait we could call it something like `develop` until it's ready.

Got it. Once we've figure out how to name things here, I'll merge this PR and then merge the `release-0.5` branch into `master`. Maybe there's not enough development going on here to keep several branches going.

**Comment by ludvigak** [comment]
So, how about this strucure:
- All types and functions have the `gsl_` prefix dropped. We encourage `import` rather than `using`.
- Both direct and secondary wrappers are available directly under the `GSL` namespace
- The `GSL.C` namespace has types and direct wrappers with original names, i.e. including the prefix. (Maybe `C` is not the best submodule name, but something to indicate that it's the direct C interface.)
- All constants live in the separate namespace `GSL.Const`, e.g. `GSL_CONST_MKS_SPEED_OF_LIGHT` becomes `GSL.Const.MKS_SPEED_OF_LIGHT`.

**Comment by yuyichao** [comment]
> The GSL.C namespace has types and direct wrappers with original names, i.e. including the prefix. (Maybe C is not the best submodule name, but something to indicate that it's the direct C interface.)

What's the point of the prefix here? I mean, it's not needed to distinguish the function, you've already got a namespace, and it doesn't help people to find the name, all functions in libgsl has the `gsl_` prefix so it's trival to find the right function to use without the `gsl_` prefix.

> `GSL.Const.MKS_SPEED_OF_LIGHT`

A bit strange for my taste but since that's how gsl names it I'm totally fine with this...

> I think he could've meant "repo"

Yes.......................... Not the first time I'm make this typo.........................

**Comment by ludvigak** [comment]
> What's the point of the prefix here? I mean, it's not needed to distinguish the function, you've already got a namespace, and it doesn't help people to find the name, all functions in libgsl has the `gsl_` prefix so it's trival to find the right function to use without the `gsl_` prefix.

Because by `using` that you would be able to write Julia code that looks as much as possible as the C code you would write when interacting with GSL. At least I like being able to do that, and naming is not a big deal here since it would be an "advanced" interface rather than the default.

**Comment by yuyichao** [comment]
> looks as much as possible as the C code you would write when interacting with GSL. At least I like being able to do that

Throw away a namespace (`using`) and add another one `gsl_` just feels very wrong and it's just left over thought from C. You couldn't have copied and pasted the code anyway and replacing `gsl_` with `C.` should be the simplest possible change you need to deal with.

In any case though, as long as the normal interface doesn't have C-stylel namespace in them I don't feel too strong about the low level interface that I'm not going to use so if you somehow feels extremely strong about it you can keep that.

**Comment by simonbyrne** [comment]
> I'll merge this PR and then merge the `release-0.5` branch into `master`.

Ah, I didn't realise the last release was 0.4. We should keep a `release-0.4` branch around just in case someone wants to patch the existing version, but if this becomes `master` we can just delete `release-0.5` (since it is currently the same).

**Comment by simonbyrne** [comment]
> Any thoughts on the low-lever interface namespace, `GSL.C` or something else?

That seems fine, I don't have any better suggestions.

**Pull request merged**
