### PR TITLE
Switch to BinaryProvider

### PR DESCRIPTION
**Pull request by giordano**
I've create a builder for GSL: https://github.com/giordano/GSLBuilder.jl  If I can be given access to JuliaMath organization I'm willing to transfer here the repo.

I hope this will work at least on Julia 0.6, failures on any other version are expected (BinaryProvider 0.3.0 requires Julia 0.6).  **Update**: ok, build succeeds only on Julia 0.6 (but I had to "downgrade the `build.jl` to a version of BinaryProvider compatible with Julia 0.6), but tests fail.  You should probably choose a small set of versions of Julia to support, it'd probably very difficult to make all of them work.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Be careful about transferring builder repos: if you've uploaded the your access token to travis, then anyone with commit access to the repo would effectively have access to it.

Realistically, I don't think it's worth the effort of trying to maintain support 0.6.

**Comment by simonbyrne** [comment]
Actually, I was incorrect, it isn't that broad. It does have access to `repo_deployment`, but for any public repo to which you have access (since for some reason GitHub doesn't have repo-specific permissions). In any case, I would suggest that you be slightly careful about who you give access to.

**Comment by giordano** [comment]
I've prepared a build for GSL 2.5: https://github.com/giordano/GSLBuilder.jl/releases/tag/v2.5 so we can upgrade to the latest version of the library as soon as needed

**Comment by ludvigak** [comment]
Great stuff! With this merged, we should be able to get a Julia 1.0 compatible release up and running pretty quickly.

**Comment by ludvigak** [comment]
I've put together a branch merging this pull request with #74: https://github.com/ludvigak/GSL.jl/tree/julia1

With some features removed, the tests pass on 0.7 and 1.0. However, 0.6 is now broken on Linux: https://travis-ci.org/ludvigak/GSL.jl/builds/442411753

@giordano, the `deps/deps.jl` created by your build script looks different depending on which Julia version is running it. Most importantly, it links to a different lib file!

`deps.jl` created using Julia 0.6:
```julia
## This file autogenerated by BinaryProvider.write_deps_file().
## Do not edit.
##
## Include this file within your main top-level source, and call
## `check_deps()` from within your module's `__init__()` method
const libgsl = joinpath(dirname(@__FILE__), "usr/lib/libgslcblas.so")
function check_deps()
    global libgsl
    if !isfile(libgsl)
        error("$(libgsl) does not exist, Please re-run Pkg.build(\"GSL\"), and restart Julia.")
    end

    if Libdl.dlopen_e(libgsl) == C_NULL
        error("$(libgsl) cannot be opened, Please re-run Pkg.build(\"GSL\"), and restart Julia.")
    end

end
```

`deps.jl` created using Julia 1.0:
```julia
## This file autogenerated by BinaryProvider.write_deps_file().
## Do not edit.
##
## Include this file within your main top-level source, and call
## `check_deps()` from within your module's `__init__()` method

if isdefined((@static VERSION < v"0.7.0-DEV.484" ? current_module() : @__MODULE__), :Compat)
    import Compat.Libdl
elseif VERSION >= v"0.7.0-DEV.3382"
    import Libdl
end
const libgsl = joinpath(dirname(@__FILE__), "usr/lib/libgsl.so")
function check_deps()
    global libgsl
    if !isfile(libgsl)
        error("$(libgsl) does not exist, Please re-run Pkg.build(\"GSL\"), and restart Julia.")
    end

    if Libdl.dlopen_e(libgsl) in (C_NULL, nothing)
        error("$(libgsl) cannot be opened, Please re-run Pkg.build(\"GSL\"), and restart Julia.")
    end

end
```

GSL.jl will not work when linked to `libgslcblas.so` instead of `libgsl.so`.

I don't know enough about BinaryBuilder to speculate about what causes this. Any ideas?

**Comment by giordano** [comment]
Try using as `build.jl` the original build script created by BinaryBuilder: https://github.com/giordano/GSLBuilder.jl/releases/download/v1.16/build_GSL.v1.16.0.jl  Hopefully, this will work on Julia 0.7+, but will most probably fail on Julia 0.6

**Comment by giordano** [comment]
To better explain: I didn't use the original build script because it most probably wouldn't have worked on Julia 0.6 (that scripts should require a version of BinaryProvider not available in Julia 0.6), thus I've modified it to make it backward compatible.

As Simon said, and I agree with him, it's probably not worth spending time on a Julia version that already has GSL.jl working, so if you decide to drop support for Julia 0.6 I'll change the build script.

**Comment by ludvigak** [comment]
It turns out BinaryProvider was picking the first file matching libgsl*. A simple fix was to change the LibraryProduct in the build script so that it would only match libgsl.*

https://github.com/ludvigak/GSL.jl/blob/b24af58a4075a9e9c0a14b424d85eb5d808373a8/deps/build.jl#L7

**Comment by giordano** [comment]
Nice job :+1:  Do I need to fix it here as well or are you going to open a PR against your branch?

**Comment by ludvigak** [comment]
Thanks! I'll open a new PR to my branch.

**Pull request merged**
