### PR TITLE
Support for Julia 0.6-1.0, use BinaryProvider

### PR DESCRIPTION
**Pull request by ludvigak**
This combines #74 and #77, and irons out a couple of remaining problems. Tests pass for Julia 0.6-1.0 on linux and osx: https://travis-ci.org/ludvigak/GSL.jl/builds/442440359

In order to get things working quickly, functions `deriv_central`, `deriv_forward` and `deriv_backward` have been disabled, together with their tests.

### CODE REVIEW

**Comment by ludvigak** [comment]
Is there a maintainer around who can merge this and create a new release?

**Comment by simonbyrne** [comment]
Thanks again for all your effort @ludvigak, @jagot and @giordano !

**Comment by simonbyrne** [comment]
You should also now be members of the JuliaMath repo, so should be able to merge and cut releases.

**Comment by simonbyrne** [comment]
Also, I'll tag a new release once we get the Windows CI up and running: see #79.

**Comment by ludvigak** [comment]
Sounds great, thanks for the invite!

**Comment by jagot** [comment]
@simonbyrne Thanks for the invite!

**Pull request merged**
